import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Header from '../components/Header/Header';
import { cookies } from 'next/headers';

import './global.css';
import '@myorg/assets/scss/variable.scss';
import '@myorg/assets/scss/reset.scss';

import { DEFAULT_THEME } from '../contants/application';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const pretendard = localFont({
  src: [
    {
      path: '../../../../packages/ui/assets/font/Pretendard-Black.woff2',
      weight: '900'
    },
    {
      path: '../../../../packages/ui/assets/font/Pretendard-ExtraBold.woff2',
      weight: '800'
    },
    {
      path: '../../../../packages/ui/assets/font/Pretendard-Bold.woff2',
      weight: '700'
    },
    {
      path: '../../../../packages/ui/assets/font/Pretendard-SemiBold.woff2',
      weight: '600'
    },
    {
      path: '../../../../packages/ui/assets/font/Pretendard-Medium.woff2',
      weight: '500'
    },
    {
      path: '../../../../packages/ui/assets/font/Pretendard-Regular.woff2',
      weight: '400'
    },
    {
      path: '../../../../packages/ui/assets/font/Pretendard-Light.woff2',
      weight: '300'
    },
    {
      path: '../../../../packages/ui/assets/font/Pretendard-ExtraLight.woff2',
      weight: '200'
    },
    {
      path: '../../../../packages/ui/assets/font/Pretendard-Thin.woff2',
      weight: '100'
    }
  ],
  variable: '--font-pretendard', // CSS 변수로 제공
  display: 'swap' // 기본 설정
});

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme');
  const initialTheme = themeCookie?.value || DEFAULT_THEME;

  return (
    <html lang="en" data-theme={initialTheme} className={pretendard.variable}>
      <body>
        <div>
          <Header />
          <>{children}</>
        </div>
      </body>
    </html>
  );
}
