import type { Metadata } from 'next';

import Header from '../components/Header/Header';
import { cookies } from 'next/headers';

import '@myorg/assets/scss/variable.scss';
import '@myorg/assets/scss/font.scss';
import '@myorg/assets/scss/reset.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme');
  const initialTheme = themeCookie?.value || 'light';

  return (
    <html lang="en" data-theme={initialTheme}>
      <body>
        <div>
          <Header />
          <>{children}</>
        </div>
      </body>
    </html>
  );
}
